---

- hosts: all
  sudo: yes
  gather_facts: yes


  vars:

    plone_initial_password: admin

    servers:
      - plone_version: '5.0.2'

        plone_zeo_port: 5100
        plone_client_base_port: 5080
        plone_sources:
          - "collective.recaptcha = git https://github.com/collective/collective.recaptcha.git"
        plone_buildout_extra_dir: ./meta/

      - plone_instance_name: p4

        plone_version: '4.3.7'

        plone_initial_password: admin
        plone_zeo_port: 4100
        plone_client_base_port: 4080
        plone_sources:
        plone_extra_parts:
          zopepy: |
            recipe = zc.recipe.egg
            eggs = ${buildout:eggs}
            interpreter = zopepy
            scripts = zopepy

        plone_buildout_extra: |
          allow-picked-versions = false

        plone_additional_versions:
          - "plone4.csrffixes = 1.0.9"
          - "cssselect = 0.9.1"


  pre_tasks:

    - name: Update apt cache
      apt: upgrade=yes update_cache=yes
      when: ansible_os_family == 'Debian'

  roles:

    - {
        role: ./,
        plone_config: "{{ servers[0] }}"
      }

    - {
        role: ./,
        plone_config: "{{ servers[1] }}"
      }

  tasks:
    - pip: name=httplib2

    - name: Check to see if Plone 5 is running
      uri:
        url: http://127.0.0.1:5081/Plone
        method: GET
        status_code: 200

    - name: Check to see if Plone 4.3.x is running
      uri:
        url: http://127.0.0.1:4081/Plone
        method: GET
        status_code: 200

    - stat: path=/usr/local/plone-5.0/zeoserver/main.yml
      register: st
    - fail: msg="copy of extra dir failed"
      when: not st.stat.exists

    - name: Check to see if we copied the extra buildout file
      command: "ls /usr/local/plone-5.0/zeoserver/main.yml"
