---

# Debian-family dependencies

- name: Update packages via apt
  apt: upgrade=dist update_cache=yes

- name: Ensure required packages
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - cron
    - curl
    - python-setuptools
    - python-pip
    - python-virtualenv
    - python-dev
    - libz-dev
    - libssl-dev
    - libjpeg-dev
    - libxslt1-dev
    - poppler-utils
    - lynx
    - unzip
    - supervisor
    - git
    - wv
    - socat

- name: Set virtualenv path
  set_fact: virtualenv_path=/usr/bin/

- name: Ensure supervisor is started
  when: instance_config.plone_use_supervisor
  service: name=supervisor state=started enabled=yes

- name: Set supervisor service name
  set_fact:
    supervisor_service_name: supervisor

# As of 2016-04-12, Xenial is not getting enabled by service play above
- name: Set supervisor to start on boot in Xenial
  when: instance_config.plone_use_supervisor and ansible_distribution_release == 'xenial'
  shell: systemctl enable supervisor.service

