---


###################################
# Prerequisites

- name: Ensure required packages
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - libz-dev
    - libssl-dev
    - libjpeg-dev
    - libxslt1-dev
    - poppler-utils
    - lynx-cur
    - unzip
    - supervisor
    - git
    - wv


###################################
# Users and groups

- name: Ensure plone_group
  group: name=plone_group

- name: Ensure plone_buildout
  user:
    name=plone_buildout
    group=plone_group
    generate_ssh_key=yes

- name: Ensure plone_daemon
  user:
    name=plone_daemon
    group=plone_group


####################################
# Directory structure and virtualenv

- name: Ensure base directory
  file:
    path={{ target_path }}
    state=directory

- name: Python virtualenv
  command: /usr/local/bin/virtualenv --python=python{{ python_version }} {{ target_path }}/Python-{{ python_version }}
    creates={{ target_path }}/Python-{{ python_version }}

- name: Buildout cache directory
  file:
    path={{ target_path }}/buildout-cache
    state=directory
    owner=plone_buildout
    group=plone_group

- name: Buildout cache eggs directory
  file:
    path={{ target_path }}/buildout-cache/eggs
    state=directory
    owner=plone_buildout
    group=plone_group

- name: Buildout cache downloads directory
  file:
    path={{ target_path }}/buildout-cache/downloads
    state=directory
    owner=plone_buildout
    group=plone_group

- name: Instance directory
  file:
    path={{ target_path }}/{{ instance_name }}
    state=directory
    owner=plone_buildout
    group=plone_group

- name: Copy buildout skeleton
  when: not buildout_git_repo
  copy:
    src=zeocluster/
    dest={{ target_path }}/{{ instance_name }}
    owner=plone_buildout
    group=plone_group

- name: Instance directory via git
  when: buildout_git_repo
  git:
    repo={{ buildout_git_repo }}
    force=no
    dest={{ target_path }}/{{ instance_name }}
    version={{ buildout_git_version | default('HEAD') }}
    depth=1
    accept_hostkey=yes
  sudo_user: plone_buildout

- name: Instance var directory
  file:
    path={{ target_path }}/{{ instance_name }}/var
    state=directory
    owner=plone_buildout
    group=plone_group
    mode=02770

- name: Separate backup directory
  when: backup_path
  file:
    path={{ backup_path }}
    state=directory
    owner=plone_daemon
    group=plone_group
    mode=0750

- name: Python eggs directory
  file:
    path={{ target_path }}/{{ instance_name }}/var/.python-eggs
    state=directory
    owner=plone_daemon
    group=plone_group

- name: Copy buildout template
  when: not buildout_git_repo
  template:
    src=buildout.cfg.j2
    dest={{ target_path }}/{{ instance_name }}/buildout.cfg
    owner=plone_buildout
    group=plone_group
    backup=yes


###################################
# Bootstrap and run buildout

- name: bootstrap buildout
  command: ../Python-{{ python_version }}/bin/python bootstrap.py
    creates={{ target_path }}/{{ instance_name }}/bin/buildout
    chdir={{ target_path }}/{{ instance_name }}
  sudo_user: plone_buildout

- name: run buildout
  command: bin/buildout
    chdir={{ target_path }}/{{ instance_name }}
  when: autorun_buildout
  sudo_user: plone_buildout


###################################
# cron jobs

- name: Pack cron job
  when: pack_at
  cron:
    name="Plone packing"
    job="cd {{ target_path }}/{{ instance_name }} && bin/zeopack"
    user=plone_daemon
    minute={{ pack_at["minute"] }}
    hour={{ pack_at.hour }}
    weekday={{ pack_at.weekday }}

- name: Backup cron job
  when: backup_at
  cron:
    name="Plone backup"
    job="cd /usr/local/plone/zeocluster && bin/backup"
    user=plone_daemon
    minute={{ backup_at["minute"] }}
    hour={{ backup_at.hour }}
    weekday={{ backup_at.weekday }}
